// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace SimpleWebApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250205084023_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            // AutoIncrementColumns satırı kaldırıldı
            // modelBuilder.Entity("SimpleWebApi.Models.Ogrenci", b =>
            modelBuilder.Entity("SimpleWebApi.Models.Ogrenci", entity =>
            {
                entity.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                entity.Property<string>("AdSoyad")
                    .IsRequired()
                    .HasColumnType("longtext");

                entity.HasKey("Id");

                entity.ToTable("Students");
            });

#pragma warning restore 612, 618
        }
    }
}
